version: '3.8'
services:
  postgres:
    build:
      context: postgres
    ports:
      - '5433:5432'
    volumes:
      - backend:/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - PGUSER=postgres
    build:
      context: api
    ports:
      - '5050:5000'
    depends_on:
      postgres:
        condition: service_healthy

#  client:
#    build:
#      context: client
#    ports:
#      - '3000:3000'
#    depends_on:
#      - api
#    environment:
#      - REACT_APP_COUNTRY_DATA_VISUALISER_BASE_URL=http://localhost:5050
#    volumes:
#      - frontend:/app

volumes:
  backend: {}
  frontend: {}
